# ip и port на котором должен слушать web-сервер
http_listen: ":5000"
# уровень логирования (error / warn / info / debug)
log_level: error
# путь к файлу логов
log_file: "file_prod.log"
# формат логирования
log_format_JSON: true
# Настройки СУБД
db_name: "MemoryMap"
db_url: ""