# Пример файла конфигурации для сервиса Календарь

# Настройки логирования
log: 
    # уровень логирования (error / warn / info / debug)
    #level: debug
    # путь к файлу логов
    file: 
    # формат логирования
    format_JSON: true

# Настройки веб-сервера
# ip и port на котором должен слушать web-сервер
http_listen: "0.0.0.0:8090"

# Настройки grpc-сервера    
# ip и port на котором должен слушать gRPC-сервер
grpc_listen: "0.0.0.0:50051"

# Настройки СУБД
db:     
    # виды storage (MemorySlice / MemoryMap / Postgres)
    db_name: "Postgres"
    # Строка подключения к БД
    url: "postgres://postgres:12345@localhost:5432/pg_calendar_test?sslmode=disable"
   
queue:
    user: guest
    password: guest
    #host: "0.0.0.0"
    host: "192.168.56.103"    
    port: 5672    
    exchange_name: calendar
    exchange_type: fanout
    qname: events    
    binding_key: 
    consumer_tag: 
      