global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090 #web client
        - localhost:9091 #grpc
        - localhost:9092 #scheduler
        
  - job_name: 'postgres'
    scrape_interval: 1s
    static_configs:
      - targets: ['postgresql-exporter:9187']        