global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090 #web client

  - job_name: 'grpc'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'sender'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9092']

  - job_name: 'postgres'
    scrape_interval: 1s
    static_configs:
      - targets: ['postgresql-exporter:9187']        