# Пример файла конфигурации для сервиса Календарь

# Настройки логирования
log: 
    # уровень логирования (error / warn / info / debug)
    #level: debug
    # путь к файлу логов
    file: 
    # формат логирования
    format_JSON: true

# Настройки веб-сервера
# ip и port на котором должен слушать web-сервер
http_listen: "0.0.0.0:8888"

# Настройки grpc-сервера    
# ip и port на котором должен слушать gRPC-сервер
grpc_listen: "0.0.0.0:50051"

# Настройки СУБД
db:     
    # виды storage (MemorySlice / MemoryMap / Postgres)
    name: "Postgres"
    host: localhost
    port: 5432
    user: postgres
    password: 12345
    database: pg_calendar
    ssl: disable
    # Строка подключения к БД
    #url: "postgres://postgres:12345@192.168.56.1:5432/pg_calendar?sslmode=disable"
   
      