version: "3.7"
services:
  
    postgres:
      image: postgres:10.0-alpine
      container_name: pgs_db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345           
        POSTGRES_DB: pg_calendar 
      volumes:
        - ~/.docker-calendar/postgres-data:/var/lib/postgresql/data
      ports:
        - 5432:5432         
      networks:
        - db-net        
  
    rabbitmq:
      image: rabbitmq:3.8.0-alpine
      container_name: rmq
      ports:
        - 5672:5672
        - 15672:15672
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest        
      networks:
        rabbit-net:
          aliases:
            - rabbitmq

    calendar:
      image: puzanovma/calendar
      container_name: calendar
      build:
        context: ../.
        dockerfile: ./deployments/calendar/Dockerfile
      ports:
        - 50051:50051
      volumes:
        - ../configs:/opt/calendar/configs
      networks:
        - db-net
      depends_on:
        - postgres
      restart: on-failure            

    scheduler:
      image: puzanovma/scheduler
      container_name: scheduler
      build:
        context: ../.
        dockerfile: ./deployments/scheduler/Dockerfile
      volumes:
        - ../configs:/opt/scheduler/configs
      networks:
        - db-net
        - rabbit-net
      depends_on:
        - postgres
        - rabbitmq
      restart: on-failure

    sender:
      image: puzanovma/sender
      container_name: sender
      build:
        context: ../.
        dockerfile: ./deployments/sender/Dockerfile
      volumes:
        - ../configs:/opt/sender/configs
      networks:
        - rabbit-net
      depends_on:
        - rabbitmq
      restart: on-failure          

networks:
  db-net:
    driver: bridge
  rabbit-net:
    driver: bridge