# Пример файла конфигурации для сервиса Календарь

# Настройки логирования
log: 
    # уровень логирования (error / warn / info / debug)
    level: debug
    # путь к файлу логов
    file: 
    # формат логирования
    format_JSON: true

# Настройки веб-сервера
# ip и port на котором должен слушать web-сервер
http_listen: "0.0.0.0:8888"

# Настройки grpc-сервера    
# ip и port на котором должен слушать gRPC-сервер
grpc_listen: "0.0.0.0:50051"

# Настройки СУБД
db:     
    # виды storage (MemorySlice / MemoryMap / Postgres)
    name: "Postgres"
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: 12345
    database: pg_calendar
    ssl: disable

prometheus:
    grpc_addr: "0.0.0.0:9091"
    sender_addr: "0.0.0.0:9092"